# Generated by Django 5.1.4 on 2024-12-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_title_product_avialable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
