# Generated by Django 5.1.4 on 2024-12-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_color_alter_product_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.ManyToManyField(blank=True, to='shop.theme'),
        ),
    ]
